import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import Navbar from "@/components/navbar";
import SocialLinks from "@/components/social-links";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen bg-background font-sans">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-6xl mx-auto py-10 px-4">
            <Navbar />
            <main className="max-w-4xl mx-auto">{children}</main>
            <SocialLinks />
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
